default_agent: agentcore_lang_runtime
agents:
  agentcore_lang_runtime:
    name: agentcore_lang_runtime
    entrypoint: /Users/neelagarwal/IDrive Sync/Cloud-Drive/For Cloud/MS DS UoR/Semester
      3/Data Science Practicum/Agentic AI/GenAI Projects/agentcore-tutorial/dev/01_agentcore_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/neelagarwal/IDrive Sync/Cloud-Drive/For Cloud/MS DS UoR/Semester
      3/Data Science Practicum/Agentic AI/GenAI Projects/agentcore-tutorial/dev
    aws:
      execution_role: arn:aws:iam::654654165755:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-c980c3716d
      execution_role_auto_create: false
      account: '654654165755'
      region: us-east-1
      ecr_repository: 654654165755.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_lang_runtime
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_lang_runtime-2pLJ2T84w5
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:654654165755:runtime/agentcore_lang_runtime-2pLJ2T84w5
      agent_session_id: 7f44fd13-72c9-481e-9a3a-4153ab98a2f6
    codebuild:
      project_name: bedrock-agentcore-agentcore_lang_runtime-builder
      execution_role: arn:aws:iam::654654165755:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-c980c3716d
      source_bucket: bedrock-agentcore-codebuild-sources-654654165755-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
